name: 'PR Title Checker'
on: 
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  name: Check Pull Request name
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: naveenk1223/action-pr-title@master
        with:
          regex: '(feat|chore|fix)\((sc-[0-9]{1,6})\):.*' # Regex the title should match.
          allowed_prefixes: 'feat,fix,chore' # title should start with the given prefix
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 10 # Min length of the title
          max_length: -1 # Max length of the title